### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by Harishwarrior** [AlexBesida/slikker_kit#1]
Hi, I love this project and hope to contribute more to this. Please let me know how i can help?

**Comment by olksij** [comment]
Hi Harish! I am sorry for the long delay for me reply since I was away. I am thankful for your feedback and it really motivates me! :)
Well regarding contribution. The project was started as a container for the widgets I usually implement in my other repositories. As of now, I am really focused in the writing guidelines of the Slikker Design System and was planning to use this repository as a source for widgets that follow the guidelines. 
Currently, the most of development goes internally, meaning I do not push changes since it's mostly used in my private repositories (which I haven't published yet 😉). As of yet the purpose and value of the package changes depending on the needs for these unpublished repos. I was aiming defining the stable development path for the package until the end of the Q2. Until then, it's probably clear that I would like to reimplement all of the material.dart library (still making both compatible) which definitely requires a lot of work, but the way of reimplementing it is not clear yet. I am very thankful for your interest, really! If you are interested, I may get in touch with you when the project development path will be defined :)
